### PR TITLE
Add v16 files

### PR DESCRIPTION
**Pull request by kgaonkar6**
## Description
Adds v16 PutativeDriverAnnoFuse for examples and shiy_fuse

## Related issue
#44

## Specific changes:
Renamed to just PutativeDriverAnnoFuse.tsv
Filtered clinical columns to only integrated_diagnosis and broad_histology
Added BreakpointLocation column with values "Genic","Intergenic" and "Intragenic"

## Request to reviewers:
This branch is not **up-to-date with changes in exemplary** right now I'll merge the changes once table_and_links is merged with exemplary
I've only updated the inst/extdata files and examples in all the scripts

### CODE REVIEW

**Comment by federicomarini** [comment]
I made some small edits, mainly to the line wrappings to keep R CMD check happy, and to use consistently assignment operators.

**Review by jharenza — APPROVED** [review]
can you update `caller.count` to `caller_count` while you are at it and we can call this approved?

**Comment by federicomarini** [comment]
> can you update caller.count to caller_count while you are at it and we can call this approved?

Note to self, we would then need to change accordingly the fields in the filtering function in shiny.

**Review by federicomarini — APPROVED** [review]

**Comment by federicomarini** [comment]
Conflicts solved for the future merging, I'll let @kgaonkar6 finish up the renaming and then we can proceed merging, I can do it from the CLI again

**Pull request merged**
