### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What feature is being added or bug is being addressed?
units tests for analysis functions, none for plotting

#### What was your approach?
using testthat package I've added some tests per function to check for expected output

#### What GitHub issue does your pull request address?
#10 adding unit tests 
#85 the bug is fixed now so even if starfusion calls don't have columns associated to --examine_coding_effect param of starfusion run the fusion_standardization function tests ok now.

#### Which areas should receive a particularly close look?
unit tests for plotting function 

#### Is there anything that you want to discuss further?
how/if we should check that the unit tests cover all conditions a user might face

#### Documentation Checklist

- [x] The function has examples to showcase the usage 
- [x] The function is fully documented in the package using roxygen 
- [ ] Added a vignette

#### Package Checklist

- [ ] The dependencies required for the function in this pull request have been added to [DESCRIPTION](https://github.com/d3b-center/annoFuse/blob/master/DESCRIPTION) `Imports` section, and the corresponding `NAMESPACE` directives have been added/updated
- [ ] The files needed for the function to run are in `inst/extdata`
- [x] The code was run through `styler`

### CODE REVIEW

**Comment by federicomarini** [comment]
Excellent work!

Addressing your points above:

- *plotting functions*: the test can be done by simply checking that the `gg` object is generated by the plotting function. I'm going to put together an example for that, feel free to "transfer" that to the other functions where it can apply
- *checking the coverage* of all the edge cases and so on: my favorite tool (there's of course a package for that 😄 ) is `covr`
Every now and then it is good practice to run

```
s <- covr::package_coverage()
covr::report(s)
```

This shows you nicely the lines covered and not covered.
Re: edge cases - our job is then to trigger them, i.e. if it should raise an error, then we trigger it intentionally by providing an unexpected format for example, and then say `expect_error` in the `testthat` framework

If you need more guidance, drop me a note - but I see you are well en route to getting it done!😉

**Comment by federicomarini** [comment]
Thinking out loud - it is probably beneficial to think ahead and have these test suite depend on `annoFuseData` - the `road_to_bioc` branch might be an ideal "meeting point"

**Comment by kgaonkar6** [comment]
> Excellent work!
> 
> Addressing your points above:
> 
> * _plotting functions_: the test can be done by simply checking that the `gg` object is generated by the plotting function. I'm going to put together an example for that, feel free to "transfer" that to the other functions where it can apply
> * _checking the coverage_ of all the edge cases and so on: my favorite tool (there's of course a package for that 😄 ) is `covr`
>   Every now and then it is good practice to run
> 
> ```
> s <- covr::package_coverage()
> covr::report(s)
> ```
> 
> This shows you nicely the lines covered and not covered.
> Re: edge cases - our job is then to trigger them, i.e. if it should raise an error, then we trigger it intentionally by providing an unexpected format for example, and then say `expect_error` in the `testthat` framework
> 
> If you need more guidance, drop me a note - but I see you are well en route to getting it done!😉

Thank you for all the info! This is all great advice,  I'll look into `covr` package and will definitely add some intentional error triggers and check with `expect_error`

**Comment by federicomarini** [comment]
Re: my review -> keep up the direction you took in here, and it's a wrap 😉 
At the end of the whole suite writing, we can have one round of `styler` to take care of uniforming the styles & spacing

**Comment by federicomarini** [comment]
Ok, coverage is approx at >90%, we're doing good on most of the codebase!

This line would need to get an import added to avoid a note:

https://github.com/d3b-center/annoFuse/blob/e7a155829f90000275ebc3bc23466ebc764d150e/R/zscored_annotation.R#L124

```
> checking R code for possible problems ... NOTE
  zscored_annotation: no visible global function definition for ':='
  Undefined global functions or variables:
    :=
```

EDIT: this one is already been taken care of 😉

**Comment by federicomarini** [comment]
Before the final closing of this, we'd just need to fix the note - see message above @kgaonkar6 
I could not rebase "in full safety" and had to go via command line

**Pull request merged**
