### PR TITLE
Sample specific bpplots

### PR DESCRIPTION
**Pull request by federicomarini**
... addressing @kgaonkar6 's suggestion in https://github.com/d3b-center/annoFuse/issues/37

### CODE REVIEW

**Comment by kgaonkar6** [comment]
I should have catched this in a previous PR but the downloaded file has the same gene as in BRAF BRAF in the Gene1B which shouldn't be the case I think.. if it's a easy fix can be added in this PR.
[shiny_fuseshinyfuse.txt](https://github.com/d3b-center/annoFuse/files/5131429/shiny_fuseshinyfuse.txt)

**Comment by federicomarini** [comment]
Oho, I think I know what that is.
Guess that is the "leftover" of the buttons.
Which leads me to the next question, and I'll probably best address that in a specific issue, i.e. which buttons to display in the table (and after noticing this, I would say one is the most to handle).

**Review by jharenza — APPROVED** [review]
I think this is all settled? @kgaonkar6 is going to do some plotting code updates and do a by row plotting instead of by sample plotting, but that should come in another PR.

**Comment by federicomarini** [comment]
Yep, that issue of the BRAF BRAF is not related to this one, it is better addressed elsewhere.
For me it is ready to merge - good for you as well @kgaonkar6 ?

**Review by kgaonkar6 — APPROVED** [review]
Sorry should have approved this yesterday only!

**Pull request merged**
