### PR TITLE
Filtered plots

### PR DESCRIPTION
**Pull request by federicomarini**
Introducing the filters to re-render the overview plots, according to the current selections.

Should address the proposal of https://github.com/d3b-center/annoFuse/issues/22

### CODE REVIEW

**Comment by federicomarini** [comment]
Something's messed up in the commit history, so the merge has to be done manually via command line.
If @kgaonkar6 and @jharenza are fine after reviewing, I can proceed with that 😉

**Review by jharenza — APPROVED** [review]

**Comment by jharenza** [comment]
@federicomarini - it seems that `molecular_subtype` is not showing for me in the Grouping Column. Can you check this?

**Comment by kgaonkar6** [comment]
Filtering looks good!

Just wondering if we can add previous rec_genes_plots PR changes were added to this branch? Specifically the the issue is that the legend for recurrently fused genes is on the left instead of bottom? https://github.com/d3b-center/annoFuse/blob/50e6cc5573397199f79c4b679c3ff5cf1fd41a96/R/plot_recurrent_genes.R#L116 
Screen Shot 2020-08-25 at 9 56 52 AM

**Comment by federicomarini** [comment]
> Just wondering if we can add previous rec_genes_plots PR changes were added to this branch? Specifically the the issue is that the legend for recurrently fused genes is on the left instead of bottom? 

I'm sure we can (and will) do that sequentially.
In the end, we'll anyway have all the tiny improvements into `exemplary` and that will be merged to `master`.

So, yes: if `rec_genes_plots` is approved, I'll merge it here, no probs 😉

**Review by kgaonkar6 — APPROVED** [review]

**Comment by federicomarini** [comment]
I also noticed that the two PRs work on totally disjoint sets of files - here I am just touching on Shiny code.
So it should be straightforward to merge the second one too!

**Pull request merged**
